# Generated by Django 4.1.7 on 2024-10-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplechat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='audio_url',
        ),
    ]
